[package]
name = "compositor_chromium"
version = "0.1.0"
edition = "2021"
license-file = "../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chromium_sys = { path = "chromium_sys" }
fs_extra = { workspace = true }
thiserror = { workspace = true }
widestring = "1.0.2"
log = { workspace = true }
anyhow = { workspace = true }
