services:
  smelter-demo:
    env_file: secret.env
    build: .
    environment:
      SMELTER_DEMO_API_PORT: "9081"
      SMELTER_DEMO_ROUTER_LOGGER_LEVEL: "warn"
      SMELTER_WHIP_WHEP_SERVER_PORT: "9082"
      SMELTER_LOGGER_FORMAT: compact
      SMELTER_LOGGER_LEVEL: info 
      SMELTER_SERVER_LOGGER_LEVEL: "info,wgpu_hal=warn,wgpu_core=warn"
      ENVIRONMENT: production
    ports:
      # JS API
      - 9081:9081
      # JS API
      - 9082:9082
    # AMD GPU
    # devices:
    #  - '/dev/dri'
    #
    # Nvidia GPU
    gpus: 'all'
    runtime: 'nvidia'
