use std::sync::{
    OnceLock,
    atomic::{AtomicU32, Ordering},
};

use anyhow::Result;
use inquire::Text;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Serialize, Deserialize)]
pub struct MoqInput {
    pub name: String,
}

impl MoqInput {
    pub fn serialize_register(&self) -> serde_json::Value {
        json!({
            "type": "moq_server",
            "decoder_map": {
                "h264": "ffmpeg_h264",
            }
        })
    }

    pub fn on_after_registration(&self) -> Result<()> {
        println!("Open in browser to start streaming with MoQ streamer tool:");
        println!("https://smelter-labs.github.io/tools/#moq-streamer");
        Ok(())
    }
}

pub struct MoqInputBuilder {
    name: String,
}

impl MoqInputBuilder {
    pub fn new() -> Self {
        let name = Self::generate_name();
        Self { name }
    }

    fn generate_name() -> String {
        static LAST_INPUT: OnceLock<AtomicU32> = OnceLock::new();
        let atomic_suffix = LAST_INPUT.get_or_init(|| AtomicU32::new(0));
        let suffix = atomic_suffix.fetch_add(1, Ordering::Relaxed);
        format!("input_moq_{suffix}")
    }

    pub fn prompt(self) -> Result<Self> {
        self.prompt_name()
    }

    fn prompt_name(self) -> Result<Self> {
        let name_input = Text::new("Input name (ESC for autogenerated):").prompt_skippable()?;

        match name_input {
            Some(name) if !name.trim().is_empty() => Ok(self.with_name(name)),
            None | Some(_) => Ok(self),
        }
    }

    pub fn with_name(mut self, name: String) -> Self {
        self.name = name;
        self
    }

    pub fn build(self) -> MoqInput {
        MoqInput { name: self.name }
    }
}
