use std::sync::{
    OnceLock,
    atomic::{AtomicU32, Ordering},
};

use anyhow::Result;
use inquire::{Confirm, Text};
use serde::{Deserialize, Serialize};
use serde_json::json;

const MOQ_CLIENT_DEFAULT_URL: &str = "https://localhost:443";
const MOQ_CLIENT_DEFAULT_BROADCAST_PATH: &str = "test";

#[derive(Debug, Serialize, Deserialize)]
pub struct MoqClientInput {
    pub name: String,
    pub endpoint_url: String,
    pub broadcast_path: String,
}

impl MoqClientInput {
    pub fn serialize_register(&self) -> serde_json::Value {
        json!({
            "type": "moq_client",
            "endpoint_url": self.endpoint_url,
            "disable_tls_verification": true,
            "broadcast_path": self.broadcast_path,
            "decoder_map": {
                "h264": "ffmpeg_h264",
            },
        })
    }

    pub fn on_before_registration(&self) -> Result<()> {
        // TODO: (@jbrs) Add prompt with the command to start server with `moq-cli` or `moq-relay`
        loop {
            let confirmation = Confirm::new("Is server running? [Y/n]")
                .with_default(true)
                .prompt()?;
            if confirmation {
                return Ok(());
            }
        }
    }
}

pub struct MoqClientInputBuilder {
    name: String,
    endpoint_url: String,
    broadcast_path: String,
}

impl MoqClientInputBuilder {
    pub fn new() -> Self {
        let name = Self::generate_name();
        let url = MOQ_CLIENT_DEFAULT_URL.to_string();
        let broadcast_path = MOQ_CLIENT_DEFAULT_BROADCAST_PATH.to_string();
        Self {
            name,
            endpoint_url: url,
            broadcast_path,
        }
    }

    fn generate_name() -> String {
        static LAST_INPUT: OnceLock<AtomicU32> = OnceLock::new();
        let atomic_suffix = LAST_INPUT.get_or_init(|| AtomicU32::new(0));
        let suffix = atomic_suffix.fetch_add(1, Ordering::Relaxed);
        format!("input_moq_client_{suffix}")
    }

    pub fn prompt(self) -> Result<Self> {
        self.prompt_name()?.prompt_url()?.prompt_broadcast_path()
    }

    fn prompt_name(self) -> Result<Self> {
        let name_input = Text::new("Input name (ESC for autogenerated):").prompt_skippable()?;

        match name_input {
            Some(name) if !name.trim().is_empty() => Ok(self.with_name(name)),
            None | Some(_) => Ok(self),
        }
    }

    fn prompt_url(self) -> Result<Self> {
        let url_input = Text::new("MoQ relay URL (ESC for default):")
            .with_initial_value(&self.endpoint_url)
            .prompt_skippable()?;

        match url_input {
            Some(url) if !url.trim().is_empty() => Ok(self.with_url(url)),
            None | Some(_) => Ok(self),
        }
    }

    fn prompt_broadcast_path(self) -> Result<Self> {
        let broadcast_path_input = Text::new("Broadcast path (ESC for default):")
            .with_initial_value(&self.broadcast_path)
            .prompt_skippable()?;

        match broadcast_path_input {
            Some(broadcast_path) if !broadcast_path.trim().is_empty() => {
                Ok(self.with_broadcast_path(broadcast_path))
            }
            None | Some(_) => Ok(self),
        }
    }

    pub fn with_name(mut self, name: String) -> Self {
        self.name = name;
        self
    }

    pub fn with_url(mut self, url: String) -> Self {
        self.endpoint_url = url;
        self
    }

    pub fn with_broadcast_path(mut self, broadcast_path: String) -> Self {
        self.broadcast_path = broadcast_path;
        self
    }

    pub fn build(self) -> MoqClientInput {
        MoqClientInput {
            name: self.name,
            endpoint_url: self.endpoint_url,
            broadcast_path: self.broadcast_path,
        }
    }
}
