use std::sync::{
    OnceLock,
    atomic::{AtomicU32, Ordering},
};

use anyhow::Result;
use inquire::Text;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Serialize, Deserialize)]
pub struct MoqServerInput {
    pub name: String,
    broadcast_path: String,
}

impl MoqServerInput {
    pub fn serialize_register(&self) -> serde_json::Value {
        json!({
            "type": "moq_server",
            "broadcast_path": self.broadcast_path,
            "required": true,
        })
    }

    pub fn on_after_registration(&self) -> Result<()> {
        println!("Publish to this input using moq-cli:");
        println!(
            "ffmpeg -re -readrate_initial_burst 7 -i <SOURCE_MP4> -c copy -movflags cmaf -f mp4 - | moq-cli publish --tls-disable-verify --url https://localhost:4443 --broadcast {} fmp4",
            self.broadcast_path
        );
        println!();
        Ok(())
    }
}

pub struct MoqInputBuilder {
    name: String,
    broadcast_path: String,
}

impl MoqInputBuilder {
    pub fn new() -> Self {
        let name = Self::generate_name();
        let broadcast_path = name.clone();
        Self {
            name,
            broadcast_path,
        }
    }

    fn generate_name() -> String {
        static LAST_INPUT: OnceLock<AtomicU32> = OnceLock::new();
        let atomic_suffix = LAST_INPUT.get_or_init(|| AtomicU32::new(0));
        let suffix = atomic_suffix.fetch_add(1, Ordering::Relaxed);
        format!("input_moq_{suffix}")
    }

    pub fn prompt(self) -> Result<Self> {
        self.prompt_name()?.prompt_broadcast_path()
    }

    fn prompt_name(self) -> Result<Self> {
        let name_input = Text::new("Input name (ESC for autogenerated):").prompt_skippable()?;

        match name_input {
            Some(name) if !name.trim().is_empty() => Ok(self.with_name(name)),
            None | Some(_) => Ok(self),
        }
    }

    fn prompt_broadcast_path(self) -> Result<Self> {
        let path_input = Text::new(&format!(
            "Broadcast path (ESC for '{}'):",
            self.broadcast_path
        ))
        .prompt_skippable()?;

        match path_input {
            Some(path) if !path.trim().is_empty() => Ok(self.with_broadcast_path(path)),
            None | Some(_) => Ok(self),
        }
    }

    pub fn with_name(mut self, name: String) -> Self {
        self.broadcast_path = name.clone();
        self.name = name;
        self
    }

    pub fn with_broadcast_path(mut self, broadcast_path: String) -> Self {
        self.broadcast_path = broadcast_path;
        self
    }

    pub fn build(self) -> MoqServerInput {
        MoqServerInput {
            name: self.name,
            broadcast_path: self.broadcast_path,
        }
    }
}
