use std::{
    fs,
    sync::{
        OnceLock,
        atomic::{AtomicU32, Ordering},
    },
};

use anyhow::{Context, Result};
use inquire::Text;
use serde::{Deserialize, Serialize};
use serde_json::json;
use sha2::{Digest, Sha256};
use smelter::config::read_config;
use tracing::warn;

use crate::IP;

#[derive(Debug, Serialize, Deserialize)]
pub struct MoqServerInput {
    pub name: String,
    pub auth_token: String,
}

impl MoqServerInput {
    pub fn serialize_register(&self) -> serde_json::Value {
        json!({
            "type": "moq_server",
            "decoder_map": {
                "h264": "ffmpeg_h264",
            },
            "auth_token": self.auth_token,
        })
    }

    pub fn on_after_registration(&self) -> Result<()> {
        let moq_streamer_url = "https://smelter-labs.github.io/tools/#moq-streamer";
        let config = read_config();
        let mut url = format!(
            "{moq_streamer_url}?url=https://{IP}:{}/{}&token={}",
            config.moq_server_port, self.name, self.auth_token
        );
        if config.moq_tls_config.is_none() {
            match self_signed_cert_fingerprint() {
                Ok(fingerprint) => url.push_str(&format!("&cert={fingerprint}")),
                Err(err) => warn!("Failed to read self-signed MoQ certificate: {err}"),
            }
        }
        println!("Open in browser to start streaming with MoQ streamer tool:");
        println!("{url}");
        Ok(())
    }
}

/// SHA-256 fingerprint of the self-signed certificate the server generates in
/// `~/.smelter` when no TLS config is provided.
fn self_signed_cert_fingerprint() -> Result<String> {
    let path = dirs::home_dir()
        .context("home directory not found")?
        .join(".smelter")
        .join("moq_cert.pem");
    let pem = fs::read_to_string(&path).with_context(|| format!("{}", path.display()))?;
    let base64: String = pem
        .lines()
        .filter(|line| !line.starts_with("-----"))
        .collect();
    let der = data_encoding::BASE64.decode(base64.as_bytes())?;
    Ok(data_encoding::HEXLOWER.encode(&Sha256::digest(&der)))
}

pub struct MoqServerInputBuilder {
    name: String,
    auth_token: String,
}

impl MoqServerInputBuilder {
    pub fn new() -> Self {
        let name = Self::generate_name();
        let auth_token = "example".to_string();
        Self { name, auth_token }
    }

    fn generate_name() -> String {
        static LAST_INPUT: OnceLock<AtomicU32> = OnceLock::new();
        let atomic_suffix = LAST_INPUT.get_or_init(|| AtomicU32::new(0));
        let suffix = atomic_suffix.fetch_add(1, Ordering::Relaxed);
        format!("input_moq_server_{suffix}")
    }

    pub fn prompt(self) -> Result<Self> {
        self.prompt_name()?.prompt_token()
    }

    fn prompt_name(self) -> Result<Self> {
        let name_input = Text::new("Input name (ESC for autogenerated):").prompt_skippable()?;

        match name_input {
            Some(name) if !name.trim().is_empty() => Ok(self.with_name(name)),
            None | Some(_) => Ok(self),
        }
    }

    fn prompt_token(self) -> Result<Self> {
        let token_input = Text::new("Auth token (ESC for \"example\"):").prompt_skippable()?;

        match token_input {
            Some(token) if !token.trim().is_empty() => Ok(self.with_token(token)),
            None | Some(_) => Ok(self),
        }
    }

    pub fn with_name(mut self, name: String) -> Self {
        self.name = name;
        self
    }

    pub fn with_token(mut self, auth_token: String) -> Self {
        self.auth_token = auth_token;
        self
    }

    pub fn build(self) -> MoqServerInput {
        MoqServerInput {
            name: self.name,
            auth_token: self.auth_token,
        }
    }
}
