use std::sync::{
    OnceLock,
    atomic::{AtomicU32, Ordering},
};

use anyhow::Result;
use inquire::Text;
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Debug, Serialize, Deserialize)]
pub struct MoqClientInput {
    pub name: String,
    url: String,
    broadcast_path: String,
}

impl MoqClientInput {
    pub fn serialize_register(&self) -> serde_json::Value {
        json!({
            "type": "moq_client",
            "url": self.url,
            "broadcast_path": self.broadcast_path,
            "required": true,
        })
    }
}

pub struct MoqClientInputBuilder {
    name: String,
    url: String,
    broadcast_path: String,
}

impl MoqClientInputBuilder {
    pub fn new() -> Self {
        let name = Self::generate_name();
        let broadcast_path = name.clone();
        Self {
            name,
            url: "https://localhost:4443".to_string(),
            broadcast_path,
        }
    }

    fn generate_name() -> String {
        static LAST_INPUT: OnceLock<AtomicU32> = OnceLock::new();
        let atomic_suffix = LAST_INPUT.get_or_init(|| AtomicU32::new(0));
        let suffix = atomic_suffix.fetch_add(1, Ordering::Relaxed);
        format!("input_moq_client_{suffix}")
    }

    pub fn prompt(self) -> Result<Self> {
        self.prompt_name()?.prompt_url()?.prompt_broadcast_path()
    }

    fn prompt_name(self) -> Result<Self> {
        let name_input = Text::new("Input name (ESC for autogenerated):").prompt_skippable()?;

        match name_input {
            Some(name) if !name.trim().is_empty() => Ok(self.with_name(name)),
            None | Some(_) => Ok(self),
        }
    }

    fn prompt_url(self) -> Result<Self> {
        let url_input =
            Text::new(&format!("Relay URL (ESC for '{}'):", self.url)).prompt_skippable()?;

        match url_input {
            Some(url) if !url.trim().is_empty() => Ok(Self { url, ..self }),
            None | Some(_) => Ok(self),
        }
    }

    fn prompt_broadcast_path(self) -> Result<Self> {
        let path_input = Text::new(&format!(
            "Broadcast path (ESC for '{}'):",
            self.broadcast_path
        ))
        .prompt_skippable()?;

        match path_input {
            Some(path) if !path.trim().is_empty() => Ok(Self {
                broadcast_path: path,
                ..self
            }),
            None | Some(_) => Ok(self),
        }
    }

    fn with_name(mut self, name: String) -> Self {
        self.broadcast_path = name.clone();
        self.name = name;
        self
    }

    pub fn build(self) -> MoqClientInput {
        MoqClientInput {
            name: self.name,
            url: self.url,
            broadcast_path: self.broadcast_path,
        }
    }
}
