export const fakeMessages = [
    "Hey, are you coming to the party tonight?",
    "Don't forget to bring snacks!",
    "I'll be there around 8. What about you?",
    "Lol that was hilarious 😂",
    "Can you send me the notes from class?",
    "W",
    "this streamer is actually cracked lol",
    "Almost done with the report. Sending soon!",
    "Pog",
    "LUL",
    "No worries, take your time.",
    "What’s the plan for the weekend?",
    "Can't talk right now, text you later!",
    "Let’s meet at the coffee shop at 3?",
    "That sounds perfect!",
    "YEP",
    "Huh?",
    "???",
    "!!!",
    "Just finished watching the movie. It was awesome!",
    "It’s actually insane how good this dude is. He’s doing things I didn’t even know were possible in this game.",
    "This streamer is a national treasure. The way he plays, the way he talks to chat, the raw emotion in every reaction — it's like watching an artist at work.",
    "Twitch chat, gather round and bear witness. You have just seen a play so divine, so perfect in execution, that even the esports gods weep with envy. Clip it, save it, frame it. That was legendary.",
    "Good morning! ☀️",
    "KEKW",
    "Did you see what happened on the news today?",
    "I'll call you in 5 minutes.",
    "he's cracked",
    "sheesh that's clean",
    "big W play",
    "he threw lol",
    "it's winnable",
    "mod check?",
    "pauseChamp moment",
    "spam this",
    "that timing was actually insane",
    "Who's bringing the drinks?",
    "I'm so tired today 😩",
    "Same here. Need coffee ASAP.",
    "Don't forget our meeting at 10!",
    "gg",
    "xd",
    "ok",
    "yes",
    "no",
    "F",
    "EZ",
    "Kappa",
    "Bruh",
    "new meta just dropped today",
    "actual god-tier gameplay right there",
    "No way he clutched that 1v5 with 2 HP and no armor. This guy's playing on another level.",
    "Can someone explain how he even saw that guy? Literally zero vision on my screen. Either he's hacking or I need better eyes.",
    "I’ve been watching this game for 10 minutes and I still have no clue what the objective is. Streamer’s not helping either.",
    "L",
    "Nope",
    "Running late, sorry!",
    "chat go wild",
    "yo what was that",
    "wtf",
    "he really hit that shot wow",
    "clip it before it's gone forever",
    "bro what are you doing",
    "he’s trolling on purpose I swear",
    "game sense off the charts today",
    "mods are asleep post frogs",
    "That whole sequence was peak Twitch content. Missed shots, lucky timing, random yelling, and somehow it worked out. Never change.",
    "Remember, chat, in moments like these — it’s not about winning or losing. It’s about the friends we muted along the way. Shoutout to all the backseaters who knew better but said nothing.",
    "Mods, please ban me. I’ve watched this stream for 8 hours straight, eaten nothing but cold pizza, and now I’m questioning my life choices. I need to go touch grass.",
];

const twitchProfiles = [
    { user: "ShadowSniperX", color: "#FF4F4F" },
    { user: "PixelFuryTV", color: "#FFB300" },
    { user: "NoScopeNinja", color: "#00E5FF" },
    { user: "LurkingTiger", color: "#76FF03" },
    { user: "CrimsonCaster", color: "#FF4081" },
    { user: "RageQuitQueen", color: "#FFD740" },
    { user: "EpicLootLord", color: "#7C4DFF" },
    { user: "GhostPuncher", color: "#18FFFF" },
    { user: "ClutchWizard", color: "#00E676" },
    { user: "Snipezilla99", color: "#FF1744" },
    { user: "LagBeast", color: "#F50057" },
    { user: "ManaMancer", color: "#40C4FF" },
    { user: "TiltedTornado", color: "#FF6D00" },
    { user: "CritChaser", color: "#D500F9" },
    { user: "StreamDreamer", color: "#64FFDA" },
    { user: "GlitchKnight", color: "#FF80AB" },
    { user: "BotBusterTV", color: "#EEFF41" },
    { user: "XPGrinder", color: "#00B0FF" },
    { user: "SaltFactory", color: "#FFC400" },
    { user: "GGsOnlyBro", color: "#69F0AE" },
];

export function getRandomTwitchProfile() {
    return twitchProfiles[Math.floor(Math.random() * twitchProfiles.length)];
}
