use std::env;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let srt_src = manifest_dir.join("srt");

    println!("cargo:rerun-if-changed=build.rs");
    println!(
        "cargo:rerun-if-changed={}",
        srt_src.join("srtcore").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        srt_src.join("CMakeLists.txt").display()
    );

    // openssl-sys exposes its include dir and link config.
    let openssl_include = env::var("DEP_OPENSSL_INCLUDE").ok();
    let openssl_root = openssl_include
        .as_ref()
        .and_then(|p| PathBuf::from(p).parent().map(|p| p.to_path_buf()));

    let mut cfg = cmake::Config::new(&srt_src);
    cfg.define("ENABLE_APPS", "OFF")
        .define("ENABLE_TESTING", "OFF")
        .define("ENABLE_UNITTESTS", "OFF")
        .define("ENABLE_SHARED", "OFF")
        .define("ENABLE_STATIC", "ON")
        .define("ENABLE_ENCRYPTION", "ON")
        .define("ENABLE_BONDING", "ON")
        .define("USE_OPENSSL_PC", "OFF")
        .define("ENABLE_CXX_DEPS", "OFF")
        .define("CMAKE_POLICY_VERSION_MINIMUM", "3.5");

    if let Some(root) = openssl_root {
        cfg.define("OPENSSL_ROOT_DIR", root);
    }
    if let Some(inc) = &openssl_include {
        cfg.define("OPENSSL_INCLUDE_DIR", inc);
    }

    let dst = cfg.build();

    // Install layout: {dst}/lib and {dst}/include/srt
    for sub in ["lib", "lib64"] {
        let p = dst.join(sub);
        if p.exists() {
            println!("cargo:rustc-link-search=native={}", p.display());
        }
    }
    println!("cargo:rustc-link-lib=static=srt");

    // C++ runtime (libsrt is C++ internally).
    let target = env::var("TARGET").unwrap();
    if target.contains("apple") {
        println!("cargo:rustc-link-lib=dylib=c++");
    } else if target.contains("msvc") {
        // msvc links C++ runtime automatically.
    } else {
        println!("cargo:rustc-link-lib=dylib=stdc++");
    }

    // openssl-sys emits its own link directives via DEP_OPENSSL_*.
    // Ensure libsrt can still resolve crypto/ssl at link time.
    println!("cargo:rustc-link-lib=dylib=ssl");
    println!("cargo:rustc-link-lib=dylib=crypto");

    if target.contains("windows") {
        println!("cargo:rustc-link-lib=dylib=ws2_32");
        println!("cargo:rustc-link-lib=dylib=iphlpapi");
        println!("cargo:rustc-link-lib=dylib=crypt32");
    }

    let include_dir = dst.join("include");
    let srt_include = include_dir.join("srt");

    let bindings = bindgen::Builder::default()
        .header(srt_include.join("srt.h").to_string_lossy().into_owned())
        .clang_arg(format!("-I{}", include_dir.display()))
        .clang_arg(format!("-I{}", srt_include.display()))
        .allowlist_function("srt_.*")
        .allowlist_function("SRT_.*")
        .allowlist_type("SRT.*")
        .allowlist_type("srt_.*")
        .allowlist_var("SRT.*")
        .allowlist_var("SRTO_.*")
        .derive_default(true)
        .derive_debug(true)
        .prepend_enum_name(false)
        .default_enum_style(bindgen::EnumVariation::ModuleConsts)
        .generate_comments(false)
        .layout_tests(false)
        .generate()
        .expect("failed to generate SRT bindings");

    let preamble = "\
// @generated by build.rs from srt/srtcore/srt.h — do not edit by hand.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(deref_nullptr)]
#![allow(clippy::all)]

";
    let new_contents = format!("{preamble}{bindings}");

    let bindings_rs = manifest_dir.join("src").join("bindings.rs");
    let needs_write = std::fs::read_to_string(&bindings_rs)
        .map(|existing| existing != new_contents)
        .unwrap_or(true);
    if needs_write {
        std::fs::write(&bindings_rs, new_contents).expect("failed to write src/bindings.rs");
    }
}
