use std::env;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let lib = pkg_config::Config::new()
        .probe("srt")
        .expect("failed to find `srt` via pkg-config; install libsrt and ensure `pkg-config --exists srt` succeeds");

    let mut builder = bindgen::Builder::default()
        .allowlist_function("srt_.*")
        .allowlist_function("SRT_.*")
        .allowlist_type("SRT.*")
        .allowlist_type("srt_.*")
        .allowlist_var("SRT.*")
        .allowlist_var("SRTO_.*")
        .derive_default(true)
        .derive_debug(true)
        .prepend_enum_name(false)
        .default_enum_style(bindgen::EnumVariation::ModuleConsts)
        .generate_comments(false)
        .layout_tests(false);

    for path in &lib.include_paths {
        builder = builder.clang_arg(format!("-I{}", path.display()));
    }

    let srt_header = lib
        .include_paths
        .iter()
        .map(|p| p.join("srt.h"))
        .find(|p| p.exists())
        .unwrap_or_else(|| PathBuf::from("srt/srt.h"));
    let builder = builder.header(srt_header.to_string_lossy().into_owned());

    let bindings = builder.generate().expect("failed to generate SRT bindings");

    let preamble = "\
// @generated by build.rs from <srt/srt.h> — do not edit by hand.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(deref_nullptr)]
#![allow(clippy::all)]

";
    let new_contents = format!("{preamble}{bindings}");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let bindings_rs = manifest_dir.join("src").join("bindings.rs");
    let needs_write = std::fs::read_to_string(&bindings_rs)
        .map(|existing| existing != new_contents)
        .unwrap_or(true);
    if needs_write {
        std::fs::write(&bindings_rs, new_contents).expect("failed to write src/bindings.rs");
    }
}
