packages:
  - 'smelter'
  - 'smelter-core'
  - 'smelter-node'
  - 'smelter-browser-render'
  - 'smelter-web-wasm'
  - 'smelter-web-client'
  - 'examples/node-examples'
  - 'examples/vite-example'
  - 'examples/vite-web-client'
  - 'create-smelter-app'
  - 'create-smelter-app/templates/node-minimal'
  - 'create-smelter-app/templates/node-express-zustand'
  - 'create-smelter-app/templates/node-offline-minimal'
  - 'create-smelter-app/templates/node-offline-showcase'
  # Client is not part of the workspace, it does not use SDK directlly and including
  # it would cause problems with version of React
  # - 'create-smelter-app/templates/node-next-webrtc/client'
  - 'create-smelter-app/templates/node-next-webrtc/server'
