// @generated by build.rs from srt/srtcore/srt.h — do not edit by hand.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(deref_nullptr)]
#![allow(clippy::all)]

/* automatically generated by rust-bindgen 0.72.1 */

pub const SRT_VERSION_MAJOR: u32 = 1;
pub const SRT_VERSION_MINOR: u32 = 5;
pub const SRT_VERSION_PATCH: u32 = 4;
pub const SRT_VERSION_STRING: &[u8; 6] = b"1.5.4\0";
pub const SRT_LOG_LEVEL_MIN: u32 = 2;
pub const SRT_LOG_LEVEL_MAX: u32 = 7;
pub const SRT_LOGF_DISABLE_TIME: u32 = 1;
pub const SRT_LOGF_DISABLE_THREADNAME: u32 = 2;
pub const SRT_LOGF_DISABLE_SEVERITY: u32 = 4;
pub const SRT_LOGF_DISABLE_EOL: u32 = 8;
pub const SRT_VERSION_FEAT_HSv5: u32 = 66304;
pub const SRT_HAVE_CXX17: u32 = 0;
pub const SRT_REJC_INTERNAL: u32 = 0;
pub const SRT_REJC_PREDEFINED: u32 = 1000;
pub const SRT_REJC_USERDEFINED: u32 = 2000;
pub const SRT_LOGFA_GENERAL: u32 = 0;
pub const SRT_LOGFA_SOCKMGMT: u32 = 1;
pub const SRT_LOGFA_CONN: u32 = 2;
pub const SRT_LOGFA_XTIMER: u32 = 3;
pub const SRT_LOGFA_TSBPD: u32 = 4;
pub const SRT_LOGFA_RSRC: u32 = 5;
pub const SRT_LOGFA_CONGEST: u32 = 7;
pub const SRT_LOGFA_PFILTER: u32 = 8;
pub const SRT_LOGFA_API_CTRL: u32 = 11;
pub const SRT_LOGFA_QUE_CTRL: u32 = 13;
pub const SRT_LOGFA_EPOLL_UPD: u32 = 16;
pub const SRT_LOGFA_API_RECV: u32 = 21;
pub const SRT_LOGFA_BUF_RECV: u32 = 22;
pub const SRT_LOGFA_QUE_RECV: u32 = 23;
pub const SRT_LOGFA_CHN_RECV: u32 = 24;
pub const SRT_LOGFA_GRP_RECV: u32 = 25;
pub const SRT_LOGFA_API_SEND: u32 = 31;
pub const SRT_LOGFA_BUF_SEND: u32 = 32;
pub const SRT_LOGFA_QUE_SEND: u32 = 33;
pub const SRT_LOGFA_CHN_SEND: u32 = 34;
pub const SRT_LOGFA_GRP_SEND: u32 = 35;
pub const SRT_LOGFA_INTERNAL: u32 = 41;
pub const SRT_LOGFA_QUE_MGMT: u32 = 43;
pub const SRT_LOGFA_CHN_MGMT: u32 = 44;
pub const SRT_LOGFA_GRP_MGMT: u32 = 45;
pub const SRT_LOGFA_EPOLL_API: u32 = 46;
pub const SRT_LOGFA_HAICRYPT: u32 = 6;
pub const SRT_LOGFA_APPLOG: u32 = 10;
pub const SRT_LOGFA_LASTNONE: u32 = 63;
pub const SRT_DEFAULT_SENDFILE_BLOCK: u32 = 364000;
pub const SRT_DEFAULT_RECVFILE_BLOCK: u32 = 7280000;
pub const SRT_SYNC_CLOCK_STDCXX_STEADY: u32 = 0;
pub const SRT_SYNC_CLOCK_GETTIME_MONOTONIC: u32 = 1;
pub const SRT_SYNC_CLOCK_WINQPC: u32 = 2;
pub const SRT_SYNC_CLOCK_MACH_ABSTIME: u32 = 3;
pub const SRT_SYNC_CLOCK_POSIX_GETTIMEOFDAY: u32 = 4;
pub const SRT_SYNC_CLOCK_AMD64_RDTSC: u32 = 5;
pub const SRT_SYNC_CLOCK_IA32_RDTSC: u32 = 6;
pub const SRT_SYNC_CLOCK_IA64_ITC: u32 = 7;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int64_t = ::std::os::raw::c_longlong;
pub type sa_family_t = __uint8_t;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct sockaddr {
    pub sa_len: __uint8_t,
    pub sa_family: sa_family_t,
    pub sa_data: [::std::os::raw::c_char; 14usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr_storage {
    pub ss_len: __uint8_t,
    pub ss_family: sa_family_t,
    pub __ss_pad1: [::std::os::raw::c_char; 6usize],
    pub __ss_align: __int64_t,
    pub __ss_pad2: [::std::os::raw::c_char; 112usize],
}
impl Default for sockaddr_storage {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type SRT_LOG_HANDLER_FN = ::std::option::Option<
    unsafe extern "C" fn(
        opaque: *mut ::std::os::raw::c_void,
        level: ::std::os::raw::c_int,
        file: *const ::std::os::raw::c_char,
        line: ::std::os::raw::c_int,
        area: *const ::std::os::raw::c_char,
        message: *const ::std::os::raw::c_char,
    ),
>;
pub type SRTSOCKET = i32;
pub const SRTGROUP_MASK: i32 = 1073741824;
pub type SYSSOCKET = ::std::os::raw::c_int;
pub type UDPSOCKET = SYSSOCKET;
pub mod SRT_SOCKSTATUS {
    pub type Type = ::std::os::raw::c_uint;
    pub const SRTS_INIT: Type = 1;
    pub const SRTS_OPENED: Type = 2;
    pub const SRTS_LISTENING: Type = 3;
    pub const SRTS_CONNECTING: Type = 4;
    pub const SRTS_CONNECTED: Type = 5;
    pub const SRTS_BROKEN: Type = 6;
    pub const SRTS_CLOSING: Type = 7;
    pub const SRTS_CLOSED: Type = 8;
    pub const SRTS_NONEXIST: Type = 9;
}
pub mod SRT_SOCKOPT {
    pub type Type = ::std::os::raw::c_uint;
    pub const SRTO_MSS: Type = 0;
    pub const SRTO_SNDSYN: Type = 1;
    pub const SRTO_RCVSYN: Type = 2;
    pub const SRTO_ISN: Type = 3;
    pub const SRTO_FC: Type = 4;
    pub const SRTO_SNDBUF: Type = 5;
    pub const SRTO_RCVBUF: Type = 6;
    pub const SRTO_LINGER: Type = 7;
    pub const SRTO_UDP_SNDBUF: Type = 8;
    pub const SRTO_UDP_RCVBUF: Type = 9;
    pub const SRTO_RENDEZVOUS: Type = 12;
    pub const SRTO_SNDTIMEO: Type = 13;
    pub const SRTO_RCVTIMEO: Type = 14;
    pub const SRTO_REUSEADDR: Type = 15;
    pub const SRTO_MAXBW: Type = 16;
    pub const SRTO_STATE: Type = 17;
    pub const SRTO_EVENT: Type = 18;
    pub const SRTO_SNDDATA: Type = 19;
    pub const SRTO_RCVDATA: Type = 20;
    pub const SRTO_SENDER: Type = 21;
    pub const SRTO_TSBPDMODE: Type = 22;
    pub const SRTO_LATENCY: Type = 23;
    pub const SRTO_INPUTBW: Type = 24;
    pub const SRTO_OHEADBW: Type = 25;
    pub const SRTO_PASSPHRASE: Type = 26;
    pub const SRTO_PBKEYLEN: Type = 27;
    pub const SRTO_KMSTATE: Type = 28;
    pub const SRTO_IPTTL: Type = 29;
    pub const SRTO_IPTOS: Type = 30;
    pub const SRTO_TLPKTDROP: Type = 31;
    pub const SRTO_SNDDROPDELAY: Type = 32;
    pub const SRTO_NAKREPORT: Type = 33;
    pub const SRTO_VERSION: Type = 34;
    pub const SRTO_PEERVERSION: Type = 35;
    pub const SRTO_CONNTIMEO: Type = 36;
    pub const SRTO_DRIFTTRACER: Type = 37;
    pub const SRTO_MININPUTBW: Type = 38;
    pub const SRTO_SNDKMSTATE: Type = 40;
    pub const SRTO_RCVKMSTATE: Type = 41;
    pub const SRTO_LOSSMAXTTL: Type = 42;
    pub const SRTO_RCVLATENCY: Type = 43;
    pub const SRTO_PEERLATENCY: Type = 44;
    pub const SRTO_MINVERSION: Type = 45;
    pub const SRTO_STREAMID: Type = 46;
    pub const SRTO_CONGESTION: Type = 47;
    pub const SRTO_MESSAGEAPI: Type = 48;
    pub const SRTO_PAYLOADSIZE: Type = 49;
    pub const SRTO_TRANSTYPE: Type = 50;
    pub const SRTO_KMREFRESHRATE: Type = 51;
    pub const SRTO_KMPREANNOUNCE: Type = 52;
    pub const SRTO_ENFORCEDENCRYPTION: Type = 53;
    pub const SRTO_IPV6ONLY: Type = 54;
    pub const SRTO_PEERIDLETIMEO: Type = 55;
    pub const SRTO_BINDTODEVICE: Type = 56;
    pub const SRTO_GROUPCONNECT: Type = 57;
    pub const SRTO_GROUPMINSTABLETIMEO: Type = 58;
    pub const SRTO_GROUPTYPE: Type = 59;
    pub const SRTO_PACKETFILTER: Type = 60;
    pub const SRTO_RETRANSMITALGO: Type = 61;
    pub const SRTO_E_SIZE: Type = 62;
}
pub mod SRT_SOCKOPT_DEPRECATED {
    pub type Type = ::std::os::raw::c_uint;
    pub const SRTO_DEPRECATED_END: Type = 0;
}
pub mod SRT_TRANSTYPE {
    pub type Type = ::std::os::raw::c_uint;
    pub const SRTT_LIVE: Type = 0;
    pub const SRTT_FILE: Type = 1;
    pub const SRTT_INVALID: Type = 2;
}
pub const SRT_LIVE_DEF_PLSIZE: ::std::os::raw::c_int = 1316;
pub const SRT_LIVE_MAX_PLSIZE: ::std::os::raw::c_int = 1456;
pub const SRT_LIVE_DEF_LATENCY_MS: ::std::os::raw::c_int = 120;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct CBytePerfMon {
    pub msTimeStamp: i64,
    pub pktSentTotal: i64,
    pub pktRecvTotal: i64,
    pub pktSndLossTotal: ::std::os::raw::c_int,
    pub pktRcvLossTotal: ::std::os::raw::c_int,
    pub pktRetransTotal: ::std::os::raw::c_int,
    pub pktSentACKTotal: ::std::os::raw::c_int,
    pub pktRecvACKTotal: ::std::os::raw::c_int,
    pub pktSentNAKTotal: ::std::os::raw::c_int,
    pub pktRecvNAKTotal: ::std::os::raw::c_int,
    pub usSndDurationTotal: i64,
    pub pktSndDropTotal: ::std::os::raw::c_int,
    pub pktRcvDropTotal: ::std::os::raw::c_int,
    pub pktRcvUndecryptTotal: ::std::os::raw::c_int,
    pub byteSentTotal: u64,
    pub byteRecvTotal: u64,
    pub byteRcvLossTotal: u64,
    pub byteRetransTotal: u64,
    pub byteSndDropTotal: u64,
    pub byteRcvDropTotal: u64,
    pub byteRcvUndecryptTotal: u64,
    pub pktSent: i64,
    pub pktRecv: i64,
    pub pktSndLoss: ::std::os::raw::c_int,
    pub pktRcvLoss: ::std::os::raw::c_int,
    pub pktRetrans: ::std::os::raw::c_int,
    pub pktRcvRetrans: ::std::os::raw::c_int,
    pub pktSentACK: ::std::os::raw::c_int,
    pub pktRecvACK: ::std::os::raw::c_int,
    pub pktSentNAK: ::std::os::raw::c_int,
    pub pktRecvNAK: ::std::os::raw::c_int,
    pub mbpsSendRate: f64,
    pub mbpsRecvRate: f64,
    pub usSndDuration: i64,
    pub pktReorderDistance: ::std::os::raw::c_int,
    pub pktRcvAvgBelatedTime: f64,
    pub pktRcvBelated: i64,
    pub pktSndDrop: ::std::os::raw::c_int,
    pub pktRcvDrop: ::std::os::raw::c_int,
    pub pktRcvUndecrypt: ::std::os::raw::c_int,
    pub byteSent: u64,
    pub byteRecv: u64,
    pub byteRcvLoss: u64,
    pub byteRetrans: u64,
    pub byteSndDrop: u64,
    pub byteRcvDrop: u64,
    pub byteRcvUndecrypt: u64,
    pub usPktSndPeriod: f64,
    pub pktFlowWindow: ::std::os::raw::c_int,
    pub pktCongestionWindow: ::std::os::raw::c_int,
    pub pktFlightSize: ::std::os::raw::c_int,
    pub msRTT: f64,
    pub mbpsBandwidth: f64,
    pub byteAvailSndBuf: ::std::os::raw::c_int,
    pub byteAvailRcvBuf: ::std::os::raw::c_int,
    pub mbpsMaxBW: f64,
    pub byteMSS: ::std::os::raw::c_int,
    pub pktSndBuf: ::std::os::raw::c_int,
    pub byteSndBuf: ::std::os::raw::c_int,
    pub msSndBuf: ::std::os::raw::c_int,
    pub msSndTsbPdDelay: ::std::os::raw::c_int,
    pub pktRcvBuf: ::std::os::raw::c_int,
    pub byteRcvBuf: ::std::os::raw::c_int,
    pub msRcvBuf: ::std::os::raw::c_int,
    pub msRcvTsbPdDelay: ::std::os::raw::c_int,
    pub pktSndFilterExtraTotal: ::std::os::raw::c_int,
    pub pktRcvFilterExtraTotal: ::std::os::raw::c_int,
    pub pktRcvFilterSupplyTotal: ::std::os::raw::c_int,
    pub pktRcvFilterLossTotal: ::std::os::raw::c_int,
    pub pktSndFilterExtra: ::std::os::raw::c_int,
    pub pktRcvFilterExtra: ::std::os::raw::c_int,
    pub pktRcvFilterSupply: ::std::os::raw::c_int,
    pub pktRcvFilterLoss: ::std::os::raw::c_int,
    pub pktReorderTolerance: ::std::os::raw::c_int,
    pub pktSentUniqueTotal: i64,
    pub pktRecvUniqueTotal: i64,
    pub byteSentUniqueTotal: u64,
    pub byteRecvUniqueTotal: u64,
    pub pktSentUnique: i64,
    pub pktRecvUnique: i64,
    pub byteSentUnique: u64,
    pub byteRecvUnique: u64,
}
pub mod SRT_ERRNO {
    pub type Type = ::std::os::raw::c_int;
    pub const SRT_EUNKNOWN: Type = -1;
    pub const SRT_SUCCESS: Type = 0;
    pub const SRT_ECONNSETUP: Type = 1000;
    pub const SRT_ENOSERVER: Type = 1001;
    pub const SRT_ECONNREJ: Type = 1002;
    pub const SRT_ESOCKFAIL: Type = 1003;
    pub const SRT_ESECFAIL: Type = 1004;
    pub const SRT_ESCLOSED: Type = 1005;
    pub const SRT_ECONNFAIL: Type = 2000;
    pub const SRT_ECONNLOST: Type = 2001;
    pub const SRT_ENOCONN: Type = 2002;
    pub const SRT_ERESOURCE: Type = 3000;
    pub const SRT_ETHREAD: Type = 3001;
    pub const SRT_ENOBUF: Type = 3002;
    pub const SRT_ESYSOBJ: Type = 3003;
    pub const SRT_EFILE: Type = 4000;
    pub const SRT_EINVRDOFF: Type = 4001;
    pub const SRT_ERDPERM: Type = 4002;
    pub const SRT_EINVWROFF: Type = 4003;
    pub const SRT_EWRPERM: Type = 4004;
    pub const SRT_EINVOP: Type = 5000;
    pub const SRT_EBOUNDSOCK: Type = 5001;
    pub const SRT_ECONNSOCK: Type = 5002;
    pub const SRT_EINVPARAM: Type = 5003;
    pub const SRT_EINVSOCK: Type = 5004;
    pub const SRT_EUNBOUNDSOCK: Type = 5005;
    pub const SRT_ENOLISTEN: Type = 5006;
    pub const SRT_ERDVNOSERV: Type = 5007;
    pub const SRT_ERDVUNBOUND: Type = 5008;
    pub const SRT_EINVALMSGAPI: Type = 5009;
    pub const SRT_EINVALBUFFERAPI: Type = 5010;
    pub const SRT_EDUPLISTEN: Type = 5011;
    pub const SRT_ELARGEMSG: Type = 5012;
    pub const SRT_EINVPOLLID: Type = 5013;
    pub const SRT_EPOLLEMPTY: Type = 5014;
    pub const SRT_EBINDCONFLICT: Type = 5015;
    pub const SRT_EASYNCFAIL: Type = 6000;
    pub const SRT_EASYNCSND: Type = 6001;
    pub const SRT_EASYNCRCV: Type = 6002;
    pub const SRT_ETIMEOUT: Type = 6003;
    pub const SRT_ECONGEST: Type = 6004;
    pub const SRT_EPEERERR: Type = 7000;
}
pub mod SRT_REJECT_REASON {
    pub type Type = ::std::os::raw::c_uint;
    pub const SRT_REJ_UNKNOWN: Type = 0;
    pub const SRT_REJ_SYSTEM: Type = 1;
    pub const SRT_REJ_PEER: Type = 2;
    pub const SRT_REJ_RESOURCE: Type = 3;
    pub const SRT_REJ_ROGUE: Type = 4;
    pub const SRT_REJ_BACKLOG: Type = 5;
    pub const SRT_REJ_IPE: Type = 6;
    pub const SRT_REJ_CLOSE: Type = 7;
    pub const SRT_REJ_VERSION: Type = 8;
    pub const SRT_REJ_RDVCOOKIE: Type = 9;
    pub const SRT_REJ_BADSECRET: Type = 10;
    pub const SRT_REJ_UNSECURE: Type = 11;
    pub const SRT_REJ_MESSAGEAPI: Type = 12;
    pub const SRT_REJ_CONGESTION: Type = 13;
    pub const SRT_REJ_FILTER: Type = 14;
    pub const SRT_REJ_GROUP: Type = 15;
    pub const SRT_REJ_TIMEOUT: Type = 16;
    pub const SRT_REJ_E_SIZE: Type = 17;
}
pub mod SRT_KM_STATE {
    pub type Type = ::std::os::raw::c_uint;
    pub const SRT_KM_S_UNSECURED: Type = 0;
    pub const SRT_KM_S_SECURING: Type = 1;
    pub const SRT_KM_S_SECURED: Type = 2;
    pub const SRT_KM_S_NOSECRET: Type = 3;
    pub const SRT_KM_S_BADSECRET: Type = 4;
}
pub mod SRT_EPOLL_OPT {
    pub type Type = ::std::os::raw::c_uint;
    pub const SRT_EPOLL_OPT_NONE: Type = 0;
    pub const SRT_EPOLL_IN: Type = 1;
    pub const SRT_EPOLL_OUT: Type = 4;
    pub const SRT_EPOLL_ERR: Type = 8;
    pub const SRT_EPOLL_CONNECT: Type = 4;
    pub const SRT_EPOLL_ACCEPT: Type = 1;
    pub const SRT_EPOLL_UPDATE: Type = 16;
    pub const SRT_EPOLL_ET: Type = 2147483648;
}
pub type SRT_EPOLL_T = i32;
pub mod SRT_EPOLL_FLAGS {
    pub type Type = ::std::os::raw::c_uint;
    pub const SRT_EPOLL_ENABLE_EMPTY: Type = 1;
    pub const SRT_EPOLL_ENABLE_OUTPUTCHECK: Type = 2;
}
pub type SRT_TRACEBSTATS = CBytePerfMon;
pub const SRT_INVALID_SOCK: SRTSOCKET = -1;
pub const SRT_ERROR: ::std::os::raw::c_int = -1;
unsafe extern "C" {
    pub fn srt_startup() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_cleanup() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_socket(
        arg1: ::std::os::raw::c_int,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ) -> SRTSOCKET;
}
unsafe extern "C" {
    pub fn srt_create_socket() -> SRTSOCKET;
}
unsafe extern "C" {
    pub fn srt_bind(
        u: SRTSOCKET,
        name: *const sockaddr,
        namelen: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_bind_acquire(u: SRTSOCKET, sys_udp_sock: UDPSOCKET) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_listen(u: SRTSOCKET, backlog: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_accept(
        u: SRTSOCKET,
        addr: *mut sockaddr,
        addrlen: *mut ::std::os::raw::c_int,
    ) -> SRTSOCKET;
}
unsafe extern "C" {
    pub fn srt_accept_bond(
        listeners: *const SRTSOCKET,
        lsize: ::std::os::raw::c_int,
        msTimeOut: i64,
    ) -> SRTSOCKET;
}
pub type srt_listen_callback_fn = ::std::option::Option<
    unsafe extern "C" fn(
        opaq: *mut ::std::os::raw::c_void,
        ns: SRTSOCKET,
        hsversion: ::std::os::raw::c_int,
        peeraddr: *const sockaddr,
        streamid: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
>;
unsafe extern "C" {
    pub fn srt_listen_callback(
        lsn: SRTSOCKET,
        hook_fn: srt_listen_callback_fn,
        hook_opaque: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
pub type srt_connect_callback_fn = ::std::option::Option<
    unsafe extern "C" fn(
        opaq: *mut ::std::os::raw::c_void,
        ns: SRTSOCKET,
        errorcode: ::std::os::raw::c_int,
        peeraddr: *const sockaddr,
        token: ::std::os::raw::c_int,
    ),
>;
unsafe extern "C" {
    pub fn srt_connect_callback(
        clr: SRTSOCKET,
        hook_fn: srt_connect_callback_fn,
        hook_opaque: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_connect(
        u: SRTSOCKET,
        name: *const sockaddr,
        namelen: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_connect_debug(
        u: SRTSOCKET,
        name: *const sockaddr,
        namelen: ::std::os::raw::c_int,
        forced_isn: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_connect_bind(
        u: SRTSOCKET,
        source: *const sockaddr,
        target: *const sockaddr,
        len: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_rendezvous(
        u: SRTSOCKET,
        local_name: *const sockaddr,
        local_namelen: ::std::os::raw::c_int,
        remote_name: *const sockaddr,
        remote_namelen: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_close(u: SRTSOCKET) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_getpeername(
        u: SRTSOCKET,
        name: *mut sockaddr,
        namelen: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_getsockname(
        u: SRTSOCKET,
        name: *mut sockaddr,
        namelen: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_getsockopt(
        u: SRTSOCKET,
        level: ::std::os::raw::c_int,
        optname: SRT_SOCKOPT::Type,
        optval: *mut ::std::os::raw::c_void,
        optlen: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_setsockopt(
        u: SRTSOCKET,
        level: ::std::os::raw::c_int,
        optname: SRT_SOCKOPT::Type,
        optval: *const ::std::os::raw::c_void,
        optlen: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_getsockflag(
        u: SRTSOCKET,
        opt: SRT_SOCKOPT::Type,
        optval: *mut ::std::os::raw::c_void,
        optlen: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_setsockflag(
        u: SRTSOCKET,
        opt: SRT_SOCKOPT::Type,
        optval: *const ::std::os::raw::c_void,
        optlen: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
pub type SRT_SOCKGROUPDATA = SRT_SocketGroupData_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SRT_MsgCtrl_ {
    pub flags: ::std::os::raw::c_int,
    pub msgttl: ::std::os::raw::c_int,
    pub inorder: ::std::os::raw::c_int,
    pub boundary: ::std::os::raw::c_int,
    pub srctime: i64,
    pub pktseq: i32,
    pub msgno: i32,
    pub grpdata: *mut SRT_SOCKGROUPDATA,
    pub grpdata_size: usize,
}
impl Default for SRT_MsgCtrl_ {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type SRT_MSGCTRL = SRT_MsgCtrl_;
pub const SRT_SEQNO_NONE: i32 = -1;
pub const SRT_MSGNO_NONE: i32 = -1;
pub const SRT_MSGNO_CONTROL: i32 = 0;
pub const SRT_MSGTTL_INF: ::std::os::raw::c_int = -1;
unsafe extern "C" {
    pub fn srt_msgctrl_init(mctrl: *mut SRT_MSGCTRL);
}
unsafe extern "C" {
    pub fn srt_send(
        u: SRTSOCKET,
        buf: *const ::std::os::raw::c_char,
        len: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_sendmsg(
        u: SRTSOCKET,
        buf: *const ::std::os::raw::c_char,
        len: ::std::os::raw::c_int,
        ttl: ::std::os::raw::c_int,
        inorder: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_sendmsg2(
        u: SRTSOCKET,
        buf: *const ::std::os::raw::c_char,
        len: ::std::os::raw::c_int,
        mctrl: *mut SRT_MSGCTRL,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_recv(
        u: SRTSOCKET,
        buf: *mut ::std::os::raw::c_char,
        len: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_recvmsg(
        u: SRTSOCKET,
        buf: *mut ::std::os::raw::c_char,
        len: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_recvmsg2(
        u: SRTSOCKET,
        buf: *mut ::std::os::raw::c_char,
        len: ::std::os::raw::c_int,
        mctrl: *mut SRT_MSGCTRL,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_sendfile(
        u: SRTSOCKET,
        path: *const ::std::os::raw::c_char,
        offset: *mut i64,
        size: i64,
        block: ::std::os::raw::c_int,
    ) -> i64;
}
unsafe extern "C" {
    pub fn srt_recvfile(
        u: SRTSOCKET,
        path: *const ::std::os::raw::c_char,
        offset: *mut i64,
        size: i64,
        block: ::std::os::raw::c_int,
    ) -> i64;
}
unsafe extern "C" {
    pub fn srt_getlasterror_str() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn srt_getlasterror(errno_loc: *mut ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_strerror(
        code: ::std::os::raw::c_int,
        errnoval: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn srt_clearlasterror();
}
unsafe extern "C" {
    pub fn srt_bstats(
        u: SRTSOCKET,
        perf: *mut SRT_TRACEBSTATS,
        clear: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_bistats(
        u: SRTSOCKET,
        perf: *mut SRT_TRACEBSTATS,
        clear: ::std::os::raw::c_int,
        instantaneous: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_getsockstate(u: SRTSOCKET) -> SRT_SOCKSTATUS::Type;
}
unsafe extern "C" {
    pub fn srt_epoll_create() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_epoll_clear_usocks(eid: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_epoll_add_usock(
        eid: ::std::os::raw::c_int,
        u: SRTSOCKET,
        events: *const ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_epoll_add_ssock(
        eid: ::std::os::raw::c_int,
        s: SYSSOCKET,
        events: *const ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_epoll_remove_usock(
        eid: ::std::os::raw::c_int,
        u: SRTSOCKET,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_epoll_remove_ssock(
        eid: ::std::os::raw::c_int,
        s: SYSSOCKET,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_epoll_update_usock(
        eid: ::std::os::raw::c_int,
        u: SRTSOCKET,
        events: *const ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_epoll_update_ssock(
        eid: ::std::os::raw::c_int,
        s: SYSSOCKET,
        events: *const ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_epoll_wait(
        eid: ::std::os::raw::c_int,
        readfds: *mut SRTSOCKET,
        rnum: *mut ::std::os::raw::c_int,
        writefds: *mut SRTSOCKET,
        wnum: *mut ::std::os::raw::c_int,
        msTimeOut: i64,
        lrfds: *mut SYSSOCKET,
        lrnum: *mut ::std::os::raw::c_int,
        lwfds: *mut SYSSOCKET,
        lwnum: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct SRT_EPOLL_EVENT_STR {
    pub fd: SRTSOCKET,
    pub events: ::std::os::raw::c_int,
}
pub type SRT_EPOLL_EVENT = SRT_EPOLL_EVENT_STR;
unsafe extern "C" {
    pub fn srt_epoll_uwait(
        eid: ::std::os::raw::c_int,
        fdsSet: *mut SRT_EPOLL_EVENT,
        fdsSize: ::std::os::raw::c_int,
        msTimeOut: i64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_epoll_set(eid: ::std::os::raw::c_int, flags: i32) -> i32;
}
unsafe extern "C" {
    pub fn srt_epoll_release(eid: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_setloglevel(ll: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn srt_addlogfa(fa: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn srt_dellogfa(fa: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn srt_resetlogfa(fara: *const ::std::os::raw::c_int, fara_size: usize);
}
unsafe extern "C" {
    pub fn srt_setloghandler(opaque: *mut ::std::os::raw::c_void, handler: SRT_LOG_HANDLER_FN);
}
unsafe extern "C" {
    pub fn srt_setlogflags(flags: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn srt_getsndbuffer(
        sock: SRTSOCKET,
        blocks: *mut usize,
        bytes: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_getrejectreason(sock: SRTSOCKET) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_setrejectreason(
        sock: SRTSOCKET,
        value: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_rejectreason_str(id: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn srt_getversion() -> u32;
}
unsafe extern "C" {
    pub fn srt_time_now() -> i64;
}
unsafe extern "C" {
    pub fn srt_connection_time(sock: SRTSOCKET) -> i64;
}
unsafe extern "C" {
    pub fn srt_clock_type() -> ::std::os::raw::c_int;
}
pub mod SRT_GROUP_TYPE {
    pub type Type = ::std::os::raw::c_uint;
    pub const SRT_GTYPE_UNDEFINED: Type = 0;
    pub const SRT_GTYPE_BROADCAST: Type = 1;
    pub const SRT_GTYPE_BACKUP: Type = 2;
    pub const SRT_GTYPE_E_END: Type = 3;
}
pub const SRT_GFLAG_SYNCONMSG: u32 = 1;
pub mod SRT_MemberStatus {
    pub type Type = ::std::os::raw::c_uint;
    pub const SRT_GST_PENDING: Type = 0;
    pub const SRT_GST_IDLE: Type = 1;
    pub const SRT_GST_RUNNING: Type = 2;
    pub const SRT_GST_BROKEN: Type = 3;
}
pub use self::SRT_MemberStatus::Type as SRT_MEMBERSTATUS;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SRT_SocketGroupData_ {
    pub id: SRTSOCKET,
    pub peeraddr: sockaddr_storage,
    pub sockstate: SRT_SOCKSTATUS::Type,
    pub weight: u16,
    pub memberstate: SRT_MEMBERSTATUS,
    pub result: ::std::os::raw::c_int,
    pub token: ::std::os::raw::c_int,
}
impl Default for SRT_SocketGroupData_ {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SRT_SocketOptionObject {
    _unused: [u8; 0],
}
pub type SRT_SOCKOPT_CONFIG = SRT_SocketOptionObject;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SRT_GroupMemberConfig_ {
    pub id: SRTSOCKET,
    pub srcaddr: sockaddr_storage,
    pub peeraddr: sockaddr_storage,
    pub weight: u16,
    pub config: *mut SRT_SOCKOPT_CONFIG,
    pub errorcode: ::std::os::raw::c_int,
    pub token: ::std::os::raw::c_int,
}
impl Default for SRT_GroupMemberConfig_ {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type SRT_SOCKGROUPCONFIG = SRT_GroupMemberConfig_;
unsafe extern "C" {
    pub fn srt_create_group(arg1: SRT_GROUP_TYPE::Type) -> SRTSOCKET;
}
unsafe extern "C" {
    pub fn srt_groupof(socket: SRTSOCKET) -> SRTSOCKET;
}
unsafe extern "C" {
    pub fn srt_group_data(
        socketgroup: SRTSOCKET,
        output: *mut SRT_SOCKGROUPDATA,
        inoutlen: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_create_config() -> *mut SRT_SOCKOPT_CONFIG;
}
unsafe extern "C" {
    pub fn srt_delete_config(config: *mut SRT_SOCKOPT_CONFIG);
}
unsafe extern "C" {
    pub fn srt_config_add(
        config: *mut SRT_SOCKOPT_CONFIG,
        option: SRT_SOCKOPT::Type,
        contents: *const ::std::os::raw::c_void,
        len: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn srt_prepare_endpoint(
        src: *const sockaddr,
        adr: *const sockaddr,
        namelen: ::std::os::raw::c_int,
    ) -> SRT_SOCKGROUPCONFIG;
}
unsafe extern "C" {
    pub fn srt_connect_group(
        group: SRTSOCKET,
        name: *mut SRT_SOCKGROUPCONFIG,
        arraysize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
