[package]
name = "decklink"
version = "0.1.0"
edition = "2024"
license-file = "../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bytes = { workspace = true }
thiserror = { workspace = true }
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[lints]
workspace = true
