name: Docker - build
on:
    workflow_dispatch: {}
    schedule:
      - cron: '0 0 * * 0' # once a week
    push:
        branches: [master]
        paths:
            - Dockerfile
            - .github/workflows/docker.yml
    pull_request:
        types: [opened, synchronize]
        paths:
            - Dockerfile
            - .github/workflows/docker.yml

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
    docker_build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: build_tools/docker/slim.Dockerfile

            - uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: build_tools/docker/full.Dockerfile

            - name: Build image - slim
              run: docker build -f build_tools/docker/slim.Dockerfile -t video-compositor .

            - name: Build image - full
              run: docker build -f build_tools/docker/full.Dockerfile -t video-compositor .
